name: 'Unit Tests'

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
          - '5.16'
        include:
          - perl-version: '5.36'
            os: ubuntu-latest
            coverage: true

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: perl -V
      - run: cpanm --notest --installdeps --verbose .
      - run: perl Build.PL
      - run: ./Build
      - name: Run Tests (no coverage)
        if: ${{ !matrix.coverage }}
        run: prove -wlvmb t
      - name: Run Tests (with coverage)
        if: ${{ matrix.coverage }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          cover -test -report Coveralls

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      PAUSE_USER: ${{ secrets.PAUSE_USER }}
      PAUSE_PASS: ${{ secrets.PAUSE_PASS }}

    strategy:
      matrix:
        perl-version:
          - '5.36'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: perl -V
      - run: cpanm --notest --installdeps --verbose .
      - run: cpanm MetaCPAN::Client
      - run: perl Build.PL
      - run: ./Build
      - run: ./Build deploy
